module.exports = {
    DEFAULT_REMAINING_LETTERS: 'EEEEEEEEEEEEAAAAAAAAAIIIIIIIIIOOOOOOOONNNNNNRRRRRRTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPFFHHVVWWYYKJXQZ**',
    TILE_POINT_VALUES: {
        'A': 1, 'E': 1, 'I': 1, 'O': 1, 'U': 1, 'L': 1, 'N': 1, 'S': 1, 'T': 1, 'R': 1,
        'D': 2, 'G': 2,
        'B': 3, 'C': 3, 'M': 3, 'P': 3,
        'F': 4, 'H': 4, 'V': 4, 'W': 4, 'Y': 4,
        'K': 5,
        'J': 8, 'X': 8,
        'Q': 10, 'Z': 10,

        'a': 1, 'e': 1, 'i': 1, 'o': 1, 'u': 1, 'l': 1, 'n': 1, 's': 1, 't': 1, 'r': 1,
        'd': 2, 'g': 2,
        'b': 3, 'c': 3, 'm': 3, 'p': 3,
        'f': 4, 'h': 4, 'v': 4, 'w': 4, 'y': 4,
        'k': 5,
        'j': 8, 'x': 8,
        'q': 10, 'z': 10,

        '*': 0
    },
    CATEGORY: {
        FUNCTION: 'FUNCTION',
        QUERY: 'QUERY',
        SUCCESS: 'SUCCESS',
        REQUEST: 'REQUEST',
        NONE: '',
        CONNECTED: 'CONNECTED',
        DISCONNECTED: 'DISCONNECTED'
    },
    KEYS: {
        REMAINING_LETTERS: 'remaining_letters',
        PLAYER_COUNT: 'player_count',
        BOARD_STATE: 'board_state',
        WHOSE_TURN: 'whose_turn',
        ROOM_CODE: 'room_code',
        IP1: 'ip1',
        IP2: 'ip2',
        IP3: 'ip3',
        IP4: 'ip4',
        PASS1: 'pass1',
        PASS2: 'pass2',
        PASS3: 'pass3',
        PASS4: 'pass4',
        POINTS1: 'points1',
        POINTS2: 'points2',
        POINTS3: 'points3',
        POINTS4: 'points4',
        DOCK1: 'dock1',
        DOCK2: 'dock2',
        DOCK3: 'dock3',
        DOCK4: 'dock4',
        LAST_MODIFIED: 'last_modified'
    },
    characters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
    onlyAloneNouns: ['Chef'],
    neverAloneNouns: ['Mortal', 'Heart', 'Queen',
        'Snail', 'Embrace', 'Arrow',
        'Adoration', 'Fascination', 'Fish',
        'Desire', 'Jewel', 'Serenade',
        'Tear', 'Symphony', 'Poem',
        'Kill', 'Magic', 'Longing',
        'Touch', 'Sigh', 'Wound',
        'Bat', 'Eater', 'Taste',
        'Song', 'Biter', 'Tooth',
        'Rook', 'Cheek', 'Apple',
        'Peach', 'Child', 'Lover',
        'Tail', 'Monkey', 'Passion'],
    onlyFirstInSequenceNouns: ['Heart', 'Oak', 'Acerola',
        'Enchant', 'Queen', 'Bat',
        'Tooth', 'Taste', 'Apple',
        'Peach', 'Tail', 'Monkey',
        'Umbral', 'Passion'],
    onlyLastInSequenceNouns: ['Kin', 'Solitude', 'Magic',
        'Touch', 'Sigh', 'Child',
        'Poem', 'Constellation', 'Ripple',
        'Snail'],
    nouns: ['Constellation', 'Kin', 'River',
        'Queen', 'Monkey', 'Fish',
        'Kill', 'Mandragora', 'Lacerta',
        'Corona', 'Canis', 'Orion',
        'Andromeda', 'Mortal',
        'Wound', 'Blizzard', 'Snow',
        'Passion', 'Current', 'Damiana',
        'Acerola', 'Heart', 'Snail',
        'Hornet', 'Love', 'Embrace',
        'Arrow', 'Rose', 'Dagger',
        'Adoration', 'Secret', 'Desire',
        'Jewel', 'Whisper', 'Serenade',
        'Moonlight', 'Tear', 'Symphony',
        'Sacrifice', 'Butterfly', 'Enchant',
        'Poem', 'Yearning', 'Devotion',
        'Melody', 'Starlight', 'Serenity',
        'Kiss', 'Magic', 'Dream',
        'Sentiment', 'Spark', 'Longing',
        'Touch', 'Sigh', 'Heartbeat',
        'Raindrop', 'Knife', 'Blade',
        'Wound', 'Wolf', 'Spider',
        'Bat', 'Eater', 'Spice',
        'Chef', 'Feast', 'Taste',
        'Echo', 'Lullaby', 'Breeze',
        'Mirage', 'Ember', 'Tempest',
        'Comet', 'Solitude', 'Nebula',
        'Ghost', 'Cat', 'Devil',
        'Fox', 'Trout', 'Garden',
        'Sting', 'Song', 'Murmur',
        'Monarch', 'Spirit', 'Nail',
        'Biter', 'Glimmer', 'Radiance',
        'Saber', 'Tooth', 'Tail',
        'Cheek', 'Forest', 'Pine',
        'Oak', 'Blossom', 'Cherry',
        'Peach', 'Apple', 'Snake',
        'Swallow', 'Child', 'Lover',
        'Flower', 'Petal', 'Rabbit',
        'Harvest', 'Glaive', 'Umbral',
        'Ripple', 'Vandal'],
    prepositions: ['about', 'above', 'across',
        'after', 'against', 'among',
        'around', 'before', 'behind',
        'below', 'beside', 'between',
        'in', 'inside', 'into',
        'over', 'through', 'without',
        'to', 'toward', 'under',
        'with', 'along', 'beneath',
        'beyond']
};